FROM python:3.12-slim

# コンテナ内の作業ディレクトリを設定
WORKDIR /app

# Pythonがpycファイルやディスクキャッシュを生成しないようにする
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV MY_USER=user

# 依存関係をインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#------------------------------------------
# dev only

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    jq \
    make \
    man \
    nodejs \
    npm \
    python3-venv \
    sudo \
    tmux \
    vim-gtk3 \
    wget \
    zsh && \
    rm -rf /var/lib/apt/lists/*

# install [Black](https://black.readthedocs.io/en/stable/)
# install [Flake8](https://flake8.pycqa.org/en/latest/)
# install [isort](https://pycqa.github.io/isort/index.html)
# install [mypy](https://www.mypy-lang.org/)
# install [yamllint](https://yamllint.readthedocs.io/en/stable/#)

RUN pip install --no-cache-dir black flake8 flake8-bugbear isort mypy yamllint

COPY package.json package-lock.json ./
RUN npm install --save-dev
#RUN npm install --save-dev eslint @eslint/js eslint-config-prettier eslint-plugin-prettier htmlhint prettier stylelint stylelint-config-prettier

# install [hadolint](https://github.com/hadolint/hadolint)
RUN wget -qO- "https://api.github.com/repos/hadolint/hadolint/releases/latest" | \
    jq -r '.assets[] | select(.name | contains("Linux-x86_64")) | .browser_download_url' | \
    xargs wget -qO /usr/local/bin/hadolint && \
    chmod +x /usr/local/bin/hadolint

# ユーザーを作成して切り替える
RUN useradd -ms /bin/zsh ${MY_USER} && \
    echo "${MY_USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${MY_USER} && \
    chmod 0440 /etc/sudoers.d/${MY_USER}

USER ${MY_USER}

# oh-my-zsh
RUN sh -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
RUN sed -i 's/^plugins=(git)/plugins=(docker git python tmux)/' ~/.zshrc

#------------------------------------------

# Djangoサーバーを起動
CMD ["python", "mysite/manage.py", "runserver", "0.0.0.0:8000"]
