# This workflow executes several linters on changed files based
# on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of
          # changed files within `super-linter`
          fetch-depth: 0

      - name: List files
        run: |
          pwd
          ls -la

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CSS_FILE_NAME: ./.stylelintrc.json
          DOCKERFILE_HADOLINT_FILE_NAME: ./.hadolint.yaml
          JAVASCRIPT_DEFAULT_STYLE: prettier
          JAVASCRIPT_ES_CONFIG_FILE: ./eslint.config.mjs
          PYTHON_BLACK_CONFIG_FILE: ./pyproject.toml
          PYTHON_FLAKE8_CONFIG_FILE: ./setup.cfg
          PYTHON_ISORT_CONFIG_FILE: ./pyproject.toml
          PYTHON_MYPY_CONFIG_FILE: ./pyproject.toml
          YAML_CONFIG_FILE: ./.yamllint

          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_YAML: true
